local assert = require("luassert")

describe("parse_info_string_params", function()
    local chunk = require("r.chunk")

    it("parses simple language without params", function()
        local lang, params = chunk.parse_info_string_params("r")
        assert.same("r", lang)
        assert.same({}, params)
    end)

    it("parses {r} with braces", function()
        local lang, params = chunk.parse_info_string_params("{r}")
        assert.same("r", lang)
        assert.same({}, params)
    end)

    it("parses language with single param", function()
        local lang, params = chunk.parse_info_string_params("{bash, eval=FALSE}")
        assert.same("bash", lang)
        assert.same({ eval = "FALSE" }, params)
    end)

    it("parses language with multiple params", function()
        local lang, params = chunk.parse_info_string_params("{r, eval=FALSE, echo=TRUE}")
        assert.same("r", lang)
        assert.same({ eval = "FALSE", echo = "TRUE" }, params)
    end)

    it("parses params with spaces around equals", function()
        local lang, params = chunk.parse_info_string_params("{r, eval = FALSE}")
        assert.same("r", lang)
        assert.same({ eval = "FALSE" }, params)
    end)

    it("strips quotes from quoted values", function()
        local lang, params = chunk.parse_info_string_params('{r, child="other.Rmd"}')
        assert.same("r", lang)
        assert.same({ child = "other.Rmd" }, params)
    end)

    it("strips single quotes from values", function()
        local lang, params = chunk.parse_info_string_params("{r, child='other.Rmd'}")
        assert.same("r", lang)
        assert.same({ child = "other.Rmd" }, params)
    end)

    it("returns empty string for nil input", function()
        local lang, params = chunk.parse_info_string_params(nil)
        assert.same("", lang)
        assert.same({}, params)
    end)

    it("returns empty string for empty string input", function()
        local lang, params = chunk.parse_info_string_params("")
        assert.same("", lang)
        assert.same({}, params)
    end)

    it("handles whitespace-padded info string", function()
        local lang, params = chunk.parse_info_string_params("  {python}")
        assert.same("python", lang)
        assert.same({}, params)
    end)

    it("parses python with single quoted engine param", function()
        local lang, params = chunk.parse_info_string_params("{python, engine='reticulate'}")
        assert.same("python", lang)
        assert.same({ engine = "reticulate" }, params)
    end)
end)

describe("resolve_lang", function()
    local chunk = require("r.chunk")

    it("resolves r by direct match", function()
        local canonical, cfg = chunk.resolve_lang("r")
        assert.same("r", canonical)
        assert.truthy(cfg)
        assert.truthy(cfg.wrap_inline)
    end)

    it("resolves bash by direct match", function()
        local canonical, cfg = chunk.resolve_lang("bash")
        assert.same("bash", canonical)
        assert.truthy(cfg)
        assert.truthy(cfg.wrap_file)
    end)

    it("resolves python by direct match", function()
        local canonical, cfg = chunk.resolve_lang("python")
        assert.same("python", canonical)
        assert.truthy(cfg)
    end)

    it("resolves webr alias to r", function()
        local canonical, cfg = chunk.resolve_lang("webr")
        assert.same("r", canonical)
        assert.truthy(cfg)
    end)

    it("resolves pyodide alias to python", function()
        local canonical, cfg = chunk.resolve_lang("pyodide")
        assert.same("python", canonical)
        assert.truthy(cfg)
    end)

    it("returns nil for unknown language", function()
        local canonical, cfg = chunk.resolve_lang("javascript")
        assert.is_nil(canonical)
        assert.is_nil(cfg)
    end)

    it("returns nil for empty string", function()
        local canonical, cfg = chunk.resolve_lang("")
        assert.is_nil(canonical)
        assert.is_nil(cfg)
    end)
end)
