local assert = require("luassert")

-- The Object Browser line format is generated by R's nvimcom package.
-- The format is: indentation + type_prefix + "#" + name + "\t" + extra
-- Top-level objects have "#" at position 5 (4 spaces + "#")
-- Since we can't run R in tests, we test with synthetic lines.

describe("browser.get_name top-level parsing", function()
    local browser = require("r.browser")

    it("returns plain object name for normal R name", function()
        -- Top-level: 4 spaces + "#" + name (idx==5)
        local line = "    #myvar\t"
        local name = browser.get_name(3, line)
        assert.same("myvar", name)
    end)

    it("backtick-escapes names starting with digits", function()
        local line = "    #123var\t"
        local name = browser.get_name(3, line)
        assert.same("`123var`", name)
    end)

    it("backtick-escapes names starting with underscore", function()
        local line = "    #_private\t"
        local name = browser.get_name(3, line)
        assert.same("`_private`", name)
    end)

    it("backtick-escapes names with spaces", function()
        local line = "    #my name\t"
        local name = browser.get_name(3, line)
        assert.same("`my name`", name)
    end)

    it("backtick-escapes R reserved words", function()
        local line = "    #if\t"
        local name = browser.get_name(3, line)
        assert.same("`if`", name)
    end)

    it("backtick-escapes NULL", function()
        local line = "    #NULL\t"
        local name = browser.get_name(3, line)
        assert.same("`NULL`", name)
    end)

    it("passes through unnamed list element [[1]]", function()
        local line = "    #[[1]]\t"
        local name = browser.get_name(3, line)
        assert.same("[[1]]", name)
    end)

    it("returns empty for lines before row 3", function()
        local line = "    #myvar\t"
        local name = browser.get_name(1, line)
        assert.same("", name)
    end)
end)
